# Generated by Django 4.2.2 on 2023-08-07 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_fecha_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_create',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 15, 3, 29, 413119)),
        ),
    ]
