# Generated by Django 4.2.2 on 2023-08-06 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_fecha_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_create',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 19, 11, 8, 780624)),
        ),
    ]
