# Generated by Django 4.2.2 on 2023-08-05 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='notas',
        ),
        migrations.AddField(
            model_name='orden',
            name='horometro',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 18, 41, 46, 816632)),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_create',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 18, 41, 46, 816632)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 18, 41, 46, 815626)),
        ),
    ]
