# Generated by Django 4.2.2 on 2023-08-07 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_orden_estado_alter_orden_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecausas',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Causa', 'verbose_name_plural': 'Detalle de Causas'},
        ),
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Producto', 'verbose_name_plural': 'Detalle de Productos'},
        ),
        migrations.AlterModelOptions(
            name='detalleservicio',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de servicio', 'verbose_name_plural': 'Detalle de servicios'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['id'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['id'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 15, 3, 29, 415150)),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_create',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 15, 3, 29, 415150)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 15, 3, 29, 414134)),
        ),
    ]
